declare const API_URL: string;
declare const GENERATED_CONNECTED_REALM_ID: number;

const LOCAL_API_URL = API_URL;
const LOCAL_GENERATED_CONNECTED_REALM_ID = GENERATED_CONNECTED_REALM_ID;

export { LOCAL_API_URL as API_URL };
export { LOCAL_GENERATED_CONNECTED_REALM_ID as GENERATED_CONNECTED_REALM_ID };
