declare const BASE_URL: string
declare const GENERATED_CONNECTED_REALM_ID: number

const _BASE_URL = BASE_URL
const _GENERATED_CONNECTED_REALM_ID = GENERATED_CONNECTED_REALM_ID

export { _BASE_URL as BASE_URL }
export { _GENERATED_CONNECTED_REALM_ID as GENERATED_CONNECTED_REALM_ID }