declare const API_URL: string;
declare const GENERATED_CONNECTED_REALM_ID: number;

const _API_URL = API_URL;
const _GENERATED_CONNECTED_REALM_ID = GENERATED_CONNECTED_REALM_ID;

export { _API_URL as API_URL };
export { _GENERATED_CONNECTED_REALM_ID as GENERATED_CONNECTED_REALM_ID };
